AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /intro
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  Table: 
    Type: AWS::Serverless::SimpleTable 
    Properties: 
      PrimaryKey: 
         Name: greetings 
         Type: String 
      ProvisionedThroughput: 
         ReadCapacityUnits: 2 
         WriteCapacityUnits: 2 