AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sujeeth-sam-deployment/5a3fa0059ee5658f8b67a877102cf5bf
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 3
